/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package games.hangman.gui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcel
 */
public class InputWordDLG extends javax.swing.JDialog
{

    private boolean ok = false;
    private String word;

    /**
     * Creates new form InputWordDLG
     */
    public InputWordDLG(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.setSize(400,150);
        this.setLocationRelativeTo(parent);
        

    }
    /**
     * Returns true if the player entered a accepted string else false
     * @return 
     */
    public boolean isOk()
    {
        return ok;
    }
    
    /**
     * Returns the entered word
     * @return 
     */
    public String getWord()
    {
        return word;
    }

    /**
     * Checks if the text is a accepted word
     * @param text
     * @return 
     */
    public boolean checkWord(String text)
    {
        boolean accepted = true;
        for (int i = 0; i < text.length(); i++)
        {
            Character c = text.charAt(i);
            if (!Character.isLetter(c))
            {
                accepted = false;
            }
        }
        return accepted;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter a word");
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onCancel(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Choose");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onChoose(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        tfInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfInput, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Funktion of the choose button
     * Reads the word and sets the word if the text is valid
     * @param evt 
     */
    private void onChoose(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onChoose
    {//GEN-HEADEREND:event_onChoose
        String text = tfInput.getText();
        text =  text.trim();
        if (text.length() <= 0 || text.length() >= 20)
        {
            JOptionPane.showMessageDialog(this, "Length must be between 0 and 20");
        } else
        {
            if (checkWord(text))
            {
                word= text.toLowerCase();
                ok=true;
                this.dispose();
            } else
            {
                JOptionPane.showMessageDialog(this, "Only Letters");
            }
        }
    }//GEN-LAST:event_onChoose

    /**
     * Cancels the dialog
     * @param evt 
     */
    private void onCancel(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onCancel
    {//GEN-HEADEREND:event_onCancel
        this.dispose();
    }//GEN-LAST:event_onCancel

    public static void main(String[] args)
    {
        new InputWordDLG(null, true).setVisible(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfInput;
    // End of variables declaration//GEN-END:variables
}
